language: php

php: [5.4, 5.5]

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

before_script:
  - composer install --prefer-source --no-interaction --no-progress
  - export PATH=./bin:$PATH
  - mysql -e 'create database test; CREATE TABLE `test` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT,`name` varchar(255) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=latin1;' -utravis

script:
  -  php vendor/bin/behat
