parameters:
  dbalextension.connection_context_initializer.class: Behat\DbalExtension\Context\Initializer\ConnectionAwareInitializer
  dbalextension.collection_context_initializer.class: Behat\DbalExtension\Context\Initializer\CollectionAwareInitializer
  dbalextension.default_connection.class: Doctrine\DBAL\Driver\Connection\ConnectionInterface
  dbalextension.connection.collection.class: Behat\DbalExtension\Collection\ConnectionCollection
  dbalextension.connection.collection.factory.class: Behat\DbalExtension\Collection\Factory

services:
  dbalextension.connection.collection.factory:
    class: "%dbalextension.connection.collection.factory.class%"
    arguments:
      - "%dbalextension.config%"

  dbalextension.connection.collection:
    class: "%dbalextension.connection.collection.class%"
    factory: ["@dbalextension.connection.collection.factory", "factory"]

  dbalextension.default_connection:
    class: "%dbalextension.default_connection.class%"
    factory: ["@dbalextension.connection.collection", "get"]
    arguments: ["%dbalextension.config.default_connection_alias%"]

  dbalextension.connection_context_initializer:
    class: "%dbalextension.connection_context_initializer.class%"
    arguments: ["@dbalextension.default_connection"]
    tags:
      -  { name: context.initializer }

  dbalextension.collection_context_initializer:
    class: "%dbalextension.collection_context_initializer.class%"
    arguments:
      - "%dbalextension.config.default_connection_alias%"
      - "@dbalextension.connection.collection"
    tags:
      -  { name: context.initializer }

